name: flutter_device_compass_example
description: Demonstrates how to use the flutter_device_compass plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_device_compass:
    path: ../
  permission_handler: ^11.3.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/compass.jpg
