name: flutter_compass_v2
description: A Flutter compass. The heading varies from 0-360, 0 being north.
version: 1.1.0
homepage: https://github.com/nafiskabbo/flutter_compass_v2

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.15.0 <4.0.0"
  flutter: ">=1.12.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.hemanthraj.fluttercompass
        pluginClass: FlutterCompassPlugin
      ios:
        pluginClass: FlutterCompassPlugin
